### PR TITLE
chore: update minor versions

### PR DESCRIPTION
**Pull request by abdonrd**
I just update minor and patch versions. No majors.

Let's see in the CI if it works...

### CODE REVIEW

**Comment by abdonrd** [comment]
Ping to @bennypowers !

**Comment by abdonrd** [comment]
@bennypowers I just pin the `@pwrs/eslint-config` version to fix the CI error:

https://github.com/apollo-elements/apollo-elements/runs/4302262858?check_suite_focus=true

**Comment by abdonrd** [comment]
https://github.com/apollo-elements/apollo-elements/runs/4308204718?check_suite_focus=true#step:8:9

>Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag

@bennypowers we should skip this step?

**Comment by bennypowers** [comment]
we should have that variable set
so either
- somehow since it's your PR it doesn't get the var
- the github action is broken
- i accidentally deleted the var

**Comment by abdonrd** [comment]
Ouch! Could any of the dependencies that I have updated affect?

**Comment by bennypowers** [comment]
no it would be the github action version in the workflow file
i'd prefer not to skip this one since it is supposed to report on the coverage of the pr

i see there was recently a 3.0 release https://github.com/paambaati/codeclimate-action

**Comment by bennypowers** [comment]
LGTM thanks

It's always these "oh i'll just bump some patch deps" PRs that end up taking way longer than you'd expect

**Pull request merged**
